basefolder.name=test-output/ExtentReport
basefolder.datetimepattern=d-MMM-YY_HH-mm-ss

extent.reporter.spark.start=true
extent.reporter.spark.out=test-output/ExtentReport/Spark.html

screenshot.dir=test-output/ExtentReport/screenshots/
screenshot.rel.path=./screenshots/


#This embeds screenshots directly inside HTML as Base64.
#extent.reporter.spark.base64imagesrc=true